# Generated by Django 3.2.12 on 2024-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chef_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
