# Generated by Django 3.2.12 on 2024-03-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('src', models.CharField(max_length=250)),
            ],
        ),
    ]
